promise.then(f1).catch(f2);

promise.then(f1, f2);

Оба варианта выполняют f1 при успешном выполнении промиса
и выполняют f2 при ошибке в промисе, поэтому они эквивалентны